site_name: Documatro 3000
site_author: Benjamin

theme:
  name: material
  palette:
    # Mode sombre par défaut
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Mode clair
    # Mode clair basculable
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Mode sombre
  features:
    - navigation.expand
    - content.code.copy # Ajoute un bouton pour copier les commandes en un clic

nav:
  - Accueil: index.md
  - OverTheWire:
      - Bandit 0: bandit0.md
      - Bandit 1: bandit1.md
      - Bandit 2: bandit2.md
      - Bandit 3: bandit3.md