site_name: Documatro 3000
site_author: Benjamin

theme:
  name: material
  palette:
    # Mode sombre par défaut
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Mode clair
    # Mode clair basculable
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Mode sombre
  features:
    - navigation.expand
    - content.code.copy # Ajoute un bouton pour copier les commandes en un clic

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - attr_list # Permet de redimensionner et d'aligner les images
  - md_in_html
  - pymdownx.blocks.caption # Ajoute une légende propre sous les images
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.superfences
  

nav:
  - Accueil: index.md
  - OverTheWire:
    - Bandit:
      - Intro: bandit/intro.md
      - Bandit 0: bandit/bandit0.md
      - Bandit 1: bandit/bandit1.md
      - Bandit 2: bandit/bandit2.md
      - Bandit 3: bandit/bandit3.md
    #- Pwn.college:
    #- Root-Me:
    #- HackTheBox:
    #- SadServer:
    #- TryHackMe:
  - Presentation:
    - CV: Presentation/CV.md
  - Projets:
      - Windows Server:
          - Mise en place d'une infrastructure Windows Server: Projets/Windows_Server/Mise_en_place_infrastructure.md
  # - Linux:
  # - Virtualisation:
  # - Automatisation:
  # - Scripting: